model_list:
  - model_name: gemma
    litellm_params:
      model: ollama/gemma3:12b
      api_base: http://host.docker.internal:11434
      api_key: ""  # Empty string for Ollama as it doesn't need an API key

  - model_name: qwen
    litellm_params:
      model: ollama/qwen3:14b
      api_base: http://host.docker.internal:11434
      api_key: ""

  - model_name: deepseek
    litellm_params:
      model: ollama/deepseek-r1:14b
      api_base: http://host.docker.internal:11434
      api_key: ""

  - model_name: nomic-embed
    litellm_params:
      model: ollama/nomic-embed-text
      api_base: http://host.docker.internal:11434
      api_key: ""

litellm_settings:
  drop_params: true
  set_verbose: true
  debug_mode: true

general_settings:
  master_key: ${LITELLM_API_KEY}