# Cloudflare Tunnel Configuration
# This is an example configuration for adding Agent Zero to your existing tunnel
# You'll need to update your actual tunnel configuration in Cloudflare dashboard

tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Existing services
  - hostname: n8n.jerryagenyi.xyz
    service: http://n8n:5678
    originRequest:
      httpHostHeader: n8n.jerryagenyi.xyz
  
  - hostname: litellm.jerryagenyi.xyz
    service: http://litellm:4000
    originRequest:
      httpHostHeader: litellm.jerryagenyi.xyz
  
  - hostname: flowise.jerryagenyi.xyz
    service: http://flowise:3000
    originRequest:
      httpHostHeader: flowise.jerryagenyi.xyz
  
  # New Agent Zero service
  - hostname: a0.jerryagenyi.xyz
    service: http://agent-zero:80
    originRequest:
      httpHostHeader: a0.jerryagenyi.xyz
  
  # Catch-all rule (must be last)
  - service: http_status:404
